version: '3'

services:
  mysqlsrv:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "ervamate"
      MYSQL_DATABASE: "petshop"
    ports:
      - "3306:3306"
    volumes:
      - /home/gbonespirito/Development/devops/MariaDB:/var/lib/mysql