version: '3'

services:
  mysqlsrv:
    image: mariadb:latest
    container_name: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: "ervamate"
      MYSQL_DATABASE: "petshop"
    ports:
      - "3306:3306"
    volumes:
      - /home/gbonespirito/Development/devops/MariaDB:/var/lib/mysql

  mongodbsrv:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=petshop
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ervamate
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /home/gbonespirito/Development/devops/MongoDB:/data/db